GET http://localhost:8001

###
POST http://localhost:8001/find_rate

BLAH


###
GET http://localhost:8002

###
POST http://localhost:8002/compute

{
  "order_id": 123,
  "product_id": 321,
  "quantity": 2,
  "subtotal": 20.0,
  "shipping_address": "123 Main St, Anytown USA",
  "shipping_zip": "78701",
  "total": 21.65
}

###
POST http://localhost:8002/compute

{
  "order_id": 123,
  "product_id": 321,
  "quantity": 2,
  "subtotal": 20.0,
  "shipping_address": "123 Main St, Anytown USA",
  "shipping_zip": "BLAH",
  "total": 21.65
}